version: '3.8'

services:
  # --- Bases de datos ---
  auth-db:
    image: postgres:18.3-alpine
    container_name: auth-db
    environment:
      - POSTGRES_USER=penguin
      - POSTGRES_PASSWORD=secreto
      - POSTGRES_DB=auth_db
    networks:
      - penguin-network

  station-db:
    image: postgres:18.3-alpine
    container_name: station-db
    environment:
      - POSTGRES_USER=penguin
      - POSTGRES_PASSWORD=secreto
      - POSTGRES_DB=station_db
    networks:
      - penguin-network

  reservation-db:
    image: postgres:18.3-alpine
    container_name: reservation-db
    environment:
      - POSTGRES_USER=penguin
      - POSTGRES_PASSWORD=secreto
      - POSTGRES_DB=reservation_db
    networks:
      - penguin-network

  # --- Microservicios ---

  # 1. Microservicio de Autenticación
  auth-service:
    build:
      context: .
      dockerfile: services/auth_service/Dockerfile
    container_name: auth-service
    ports:
      - "5001:5001"
    environment:
      - AUTH_SERVICE_PORT=5001
      - DB_HOST=auth-db
      - DB_NAME=auth_db
      - DB_USER=penguin
      - DB_PASS=secreto
      - JWT_SECRET=super_secret_penguin_key
    depends_on:
      - auth-db
    networks:
      - penguin-network
    volumes:
      - ./services/auth_service:/app/services/auth_service

  # 2. Microservicio de Estaciones (Mesas)
  station-service:
    build:
      context: .
      dockerfile: services/station_service/Dockerfile
    container_name: station-service
    ports:
      - "5002:5002"
    environment:
      - STATION_SERVICE_PORT=5002
      - DB_HOST=station-db
      - DB_NAME=station_db
      - DB_USER=penguin
      - DB_PASS=secreto
      - JWT_SECRET=super_secret_penguin_key
    depends_on:
      - auth-service
      - station-db
    networks:
      - penguin-network
    volumes:
      - ./services/station_service:/app/services/station_service

  # 3. Microservicio de Reservas
  reservation-service:
    build:
      context: .
      dockerfile: services/reservation_service/Dockerfile
    container_name: reservation-service
    ports:
      - "5003:5003"
    environment:
      - RESERVATION_SERVICE_PORT=5003
      - STATIONS_URL=http://station-service:5002/stations
      - DB_HOST=reservation-db
      - DB_NAME=reservation_db
      - DB_USER=penguin
      - DB_PASS=secreto
      - JWT_SECRET=super_secret_penguin_key
    depends_on:
      - auth-service
      - reservation-db
    networks:
      - penguin-network
    volumes:
      - ./services/reservation_service:/app/services/reservation_service

networks:
  penguin-network:
    driver: bridge
