version: '3.8'

services:
  # --- Bases de datos ---
  auth-db:
    image: postgres:18.3-alpine
    container_name: auth-db
    environment:
      - POSTGRES_USER=penguin
      - POSTGRES_PASSWORD=secreto
      - POSTGRES_DB=auth_db
    networks:
      - penguin-network

  station-db:
    image: postgres:18.3-alpine
    container_name: station-db
    environment:
      - POSTGRES_USER=penguin
      - POSTGRES_PASSWORD=secreto
      - POSTGRES_DB=station_db
    networks:
      - penguin-network

  reservation-db:
    image: postgres:18.3-alpine
    container_name: reservation-db
    environment:
      - POSTGRES_USER=penguin
      - POSTGRES_PASSWORD=secreto
      - POSTGRES_DB=reservation_db
    networks:
      - penguin-network

  # --- Microservicios ---

  # 1. Microservicio de Autenticación
  auth-service:
    build:
      context: .
      dockerfile: services/auth_service/Dockerfile
    container_name: auth-service
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    environment:
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
      - DB_HOST=auth-db
      - DB_NAME=${DB_AUTH_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - auth-db
    networks:
      - penguin-network
    volumes:
      - ./services/auth_service:/app/services/auth_service

  # 2. Microservicio de Estaciones (Mesas)
  station-service:
    build:
      context: .
      dockerfile: services/station_service/Dockerfile
    container_name: station-service
    ports:
      - "${STATION_SERVICE_PORT}:${STATION_SERVICE_PORT}"
    environment:
      - STATION_SERVICE_PORT=${STATION_SERVICE_PORT}
      - DB_HOST=station-db
      - DB_NAME=${DB_STATION_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - auth-service
      - station-db
    networks:
      - penguin-network
    volumes:
      - ./services/station_service:/app/services/station_service

  # 3. Microservicio de Reservas
  reservation-service:
    build:
      context: .
      dockerfile: services/reservation_service/Dockerfile
    container_name: reservation-service
    ports:
      - "${RESERVATION_SERVICE_PORT}:${RESERVATION_SERVICE_PORT}"
    environment:
      - RESERVATION_SERVICE_PORT=${RESERVATION_SERVICE_PORT}
      - STATIONS_URL=${STATIONS_URL}
      - DB_HOST=reservation-db
      - DB_NAME=${DB_RESERVATION_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - auth-service
      - reservation-db
    networks:
      - penguin-network
    volumes:
      - ./services/reservation_service:/app/services/reservation_service

networks:
  penguin-network:
    driver: bridge
